"""add metrics to analyses

Revision ID: 58e3659d0ec9
Revises: f29207f605ba
Create Date: 2026-08-22 16:27:29.271334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58e3659d0ec9'
down_revision: Union[str, Sequence[str], None] = 'f29207f605ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analyses', sa.Column('metrics', sa.JSON(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analyses', 'metrics')
    # ### end Alembic commands ###
