"""add ocr_confidence to documents

Revision ID: f29207f605ba
Revises: ce07cd92ca5e
Create Date: 2026-08-22 15:23:17.718863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f29207f605ba'
down_revision: Union[str, Sequence[str], None] = 'ce07cd92ca5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('ocr_confidence', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'ocr_confidence')
    # ### end Alembic commands ###
